version: '3.8'

services:
  demodeploy:
    image: wakiwaki2922/demodeploycicd:latest
    container_name: demodeploy
    restart: always
    ports:
      - "8181:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    mem_limit: 512m
    mem_reservation: 256m