spring:
  config:
    activate:
      on-profile: prod
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:proddb
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update

# Custom Properties
app:
  environment: Production