spring:
  config:
    activate:
      on-profile: dev
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

# Custom Properties
app:
  environment: Development