name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          chmod +x gradlew
          ./gradlew test

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew bootJar
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/demodeploycicd:latest
            ${{ secrets.DOCKER_USERNAME }}/demodeploycicd:${{ github.run_number }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read docker-compose file
        id: docker-compose
        run: echo "content=$(cat docker-compose.yml | base64)" >> $GITHUB_OUTPUT

      - name: Deploy to Portainer
        uses: SSHcom/curl-actions@v1
        with:
          url: ${{ secrets.PORTAINER_HOST }}/api/stacks?type=2&method=file&endpointId=1
          method: POST
          headers: '{
            "X-API-Key": "${{ secrets.PORTAINER_API_TOKEN }}",
            "Content-Type": "application/json"
          }'
          body: |
            {
              "name": "demodeploy",
              "fileContent": "${{ steps.docker-compose.outputs.content }}",
              "env": []
            }